spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:tcp://localhost/~/memberservice
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: create
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: gusdn04135@gmail.com
    password: tbbl mlqo akcp dubv
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
#    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분
